version: '3.8'
services:
  nestjs-db: 
    image: mysql:8.1.0
    container_name: nestjs
    restart: always
    ports:
      - "3307:3306" #pc: container
    networks:
      - nestjs-network
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_ROOT_HOST: "%"
   

networks:
  nestjs-network:

  # deamon/background mode
  # docker compose -f ./docker-compose.yaml up -d
  # docker compose -f ./docker-compose.yaml down
  # docker compose up -d