# services:
#   db: 
#     image: mysql:8.1.0
#     container_name: nestjs
#     restart: always
#     ports:
#     - "3307:3306" #pc: container
#     environment:
#       - MYSQL_ROOT_PASSWORD = 1234
#       - MYSQL_ROOT_HOST = "%"
#       - MYSQL_USER = myuser
#       - MYSQL_HOST=db
#       - MYSQL_DATABASE=mydb
# adminer:
#   image: adminer
#   depend on:
#     - db
#   ports: 
#     - "8081:8080"
#   networks:
#     - nestjs-network
#   restart: always   


  #deamon/background mode
  #docker compose -f ./docker-compose.yaml up -d
  #docker compose -f ./docker-compose.yaml down

version: '3.3'

services:
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'ndmc'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports: 
      - "3307:3306"
    networks:
      - connect
  adminer:
    image: adminer:4
    ports:
      - "8081:8080"
    networks:
      - connect
networks:
  connect:
    driver: bridge